// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://jmgrseqvrarrfcyurlwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptZ3JzZXF2cmFycmZjeXVybHdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDE3OTEsImV4cCI6MjA2MzMxNzc5MX0.Y5VShFM1v0GvlGq8d2hJf_axmVSLAkA7sHG_sHQE_n8";

// Storage seguro: evita travar quando o navegador bloqueia localStorage (ex.: iframe/privacidade)
const memoryStorage = new Map<string, string>();

const getBrowserStorage = (): Storage | undefined => {
  try {
    if (typeof window === "undefined") return undefined;
    return window.localStorage;
  } catch {
    return undefined;
  }
};

const safeStorage: Storage = {
  get length() {
    const s = getBrowserStorage();
    return s?.length ?? memoryStorage.size;
  },
  clear() {
    const s = getBrowserStorage();
    if (s) {
      s.clear();
      return;
    }
    memoryStorage.clear();
  },
  getItem(key: string) {
    const s = getBrowserStorage();
    if (s) {
      try {
        return s.getItem(key);
      } catch {
        return memoryStorage.get(key) ?? null;
      }
    }
    return memoryStorage.get(key) ?? null;
  },
  key(index: number) {
    const s = getBrowserStorage();
    if (s) {
      try {
        return s.key(index);
      } catch {
        return Array.from(memoryStorage.keys())[index] ?? null;
      }
    }
    return Array.from(memoryStorage.keys())[index] ?? null;
  },
  removeItem(key: string) {
    const s = getBrowserStorage();
    if (s) {
      try {
        s.removeItem(key);
        return;
      } catch {
        // fallback
      }
    }
    memoryStorage.delete(key);
  },
  setItem(key: string, value: string) {
    const s = getBrowserStorage();
    if (s) {
      try {
        s.setItem(key, value);
        return;
      } catch {
        // fallback
      }
    }
    memoryStorage.set(key, value);
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});